SMDX_METADATA_CONCEPTS: Concepts de métadonnées SDMX
INDICATOR_NUMBER: 'Indicateur : %nombre'
DOWNLOAD_PDF: Télécharger PDF
REVISION_HISTORY: 'Historique de révision'
STATISTICS: Statistiques de traduction
